name: Mon premier Workflow
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v4
      - name : Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
